app:
  port: 3002
  debug: true
  secret: <secret>

database:
  host: local-db
  port: 5432
  name: johnjud_db
  username: root
  password: root

jwt:
  secret: <secret>
  expires_in: 3600
  refresh_token_ttl: 604800
  issuer: <issuer>

redis:
  host: local-cache
  port: 6379
  password: ""
  dbnum: 0